basePath: /
definitions:
  main.CreateCommentRequest:
    properties:
      message:
        example: required
        type: string
      photo_id:
        type: string
    type: object
  main.LoginRequest:
    properties:
      email:
        example: aditya.kristianto@mncgroup.com
        type: string
      password:
        example: hacktiv8
        type: string
    type: object
  main.PhotoRequest:
    properties:
      caption:
        example: echo
        type: string
      photo_url:
        example: https://cdn.labstack.com/images/echo-logo.svg
        type: string
      title:
        example: echo_golang
        type: string
    type: object
  main.RegisterRequest:
    properties:
      age:
        example: 31
        type: integer
      email:
        example: aditya.kristianto@mncgroup.com
        type: string
      password:
        example: hacktiv8
        type: string
      username:
        example: aditya.kristianto
        type: string
    type: object
  main.Response:
    properties:
      error: {}
      message:
        type: string
      payload: {}
      status:
        type: integer
    type: object
  main.SocialMediaRequest:
    properties:
      name:
        example: linkedin
        type: string
      social_media_url:
        example: https://www.linkedin.com/in/aditya-kristianto
        type: string
    type: object
  main.UpdateCommentRequest:
    properties:
      message:
        example: required
        type: string
    type: object
  main.UpdateUserRequest:
    properties:
      email:
        example: aditya.kristianto@mncgroup.com
        type: string
      username:
        example: aditya.kristianto
        type: string
    type: object
host: localhost:1323
info:
  contact:
    email: kristianto.aditya@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Final Project server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Final Project API
  version: "1.0"
paths:
  /comments:
    get:
      consumes:
      - application/json
      description: To get comment
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Get comment
      tags:
      - Comments
    post:
      consumes:
      - application/json
      description: To create comment
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.CreateCommentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Create comment
      tags:
      - Comments
  /comments/{commentId}:
    delete:
      consumes:
      - application/json
      description: To delete comment
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Delete comment
      tags:
      - Comments
    put:
      consumes:
      - application/json
      description: To update comment
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: string
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.UpdateCommentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Update comment
      tags:
      - Comments
  /photos:
    get:
      consumes:
      - application/json
      description: To get photo
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Get photo
      tags:
      - Photos
    post:
      consumes:
      - application/json
      description: To create photo
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.PhotoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Create photo
      tags:
      - Photos
  /photos/{photoId}:
    delete:
      consumes:
      - application/json
      description: To delete photo
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Photo ID
        in: path
        name: photoId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Delete photo
      tags:
      - Photos
    put:
      consumes:
      - application/json
      description: To update photo
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Photo ID
        in: path
        name: photoId
        required: true
        type: string
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.PhotoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Update photo
      tags:
      - Photos
  /socialmedias:
    get:
      consumes:
      - application/json
      description: To get social media
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Get social media
      tags:
      - SocialMedias
    post:
      consumes:
      - application/json
      description: To create social media
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.SocialMediaRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Create social media
      tags:
      - SocialMedias
  /socialmedias/{socialMediaId}:
    delete:
      consumes:
      - application/json
      description: To delete social media
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Social Media ID
        in: path
        name: socialMediaId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Delete social media
      tags:
      - SocialMedias
    put:
      consumes:
      - application/json
      description: To update social media
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Social Media ID
        in: path
        name: socialMediaId
        required: true
        type: string
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.SocialMediaRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Update social media
      tags:
      - SocialMedias
  /users:
    delete:
      consumes:
      - application/json
      description: To delete user
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Delete user
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: To update user
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Update user
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - application/json
      description: To login
      parameters:
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Login
      tags:
      - Users
  /users/register:
    post:
      consumes:
      - application/json
      description: To register
      parameters:
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Register
      tags:
      - Users
schemes:
- http
swagger: "2.0"
